/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.records;


import de.samply.bbmri.negotiator.jooq.tables.Collection;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Table to store collections from the directory
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CollectionRecord extends UpdatableRecordImpl<CollectionRecord> implements Record5<Integer, String, String, Integer, Integer> {

	private static final long serialVersionUID = -1999540667;

	/**
	 * Setter for <code>public.collection.id</code>. primary key
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.collection.id</code>. primary key
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.collection.name</code>. The collection name
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.collection.name</code>. The collection name
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.collection.directory_id</code>. The directory ID, e.g. eu_bbmri_eric_collections:NL45:blood_collection
	 */
	public void setDirectoryId(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.collection.directory_id</code>. The directory ID, e.g. eu_bbmri_eric_collections:NL45:blood_collection
	 */
	public String getDirectoryId() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.collection.biobank_id</code>. The Biobank ID this collection belongs to
	 */
	public void setBiobankId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.collection.biobank_id</code>. The Biobank ID this collection belongs to
	 */
	public Integer getBiobankId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.collection.list_of_directories_id</code>. The directorie Id where the biobank belongs to
	 */
	public void setListOfDirectoriesId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.collection.list_of_directories_id</code>. The directorie Id where the biobank belongs to
	 */
	public Integer getListOfDirectoriesId() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, String, Integer, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, String, Integer, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Collection.COLLECTION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Collection.COLLECTION.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Collection.COLLECTION.DIRECTORY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Collection.COLLECTION.BIOBANK_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Collection.COLLECTION.LIST_OF_DIRECTORIES_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getDirectoryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getBiobankId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getListOfDirectoriesId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value3(String value) {
		setDirectoryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value4(Integer value) {
		setBiobankId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord value5(Integer value) {
		setListOfDirectoriesId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CollectionRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CollectionRecord
	 */
	public CollectionRecord() {
		super(Collection.COLLECTION);
	}

	/**
	 * Create a detached, initialised CollectionRecord
	 */
	public CollectionRecord(Integer id, String name, String directoryId, Integer biobankId, Integer listOfDirectoriesId) {
		super(Collection.COLLECTION);

		setValue(0, id);
		setValue(1, name);
		setValue(2, directoryId);
		setValue(3, biobankId);
		setValue(4, listOfDirectoriesId);
	}
}
