/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.records;


import de.samply.bbmri.negotiator.jooq.tables.JsonQuery;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * query table to contain json text queries
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JsonQueryRecord extends UpdatableRecordImpl<JsonQueryRecord> implements Record4<Integer, String, Timestamp, Integer> {

	private static final long serialVersionUID = -297755383;

	/**
	 * Setter for <code>public.json_query.id</code>. primary key
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.json_query.id</code>. primary key
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.json_query.json_text</code>. text of query in json format
	 */
	public void setJsonText(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.json_query.json_text</code>. text of query in json format
	 */
	public String getJsonText() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.json_query.query_create_time</code>.
	 */
	public void setQueryCreateTime(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.json_query.query_create_time</code>.
	 */
	public Timestamp getQueryCreateTime() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>public.json_query.query_id</code>.
	 */
	public void setQueryId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.json_query.query_id</code>.
	 */
	public Integer getQueryId() {
		return (Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, Timestamp, Integer> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, Timestamp, Integer> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return JsonQuery.JSON_QUERY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return JsonQuery.JSON_QUERY.JSON_TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return JsonQuery.JSON_QUERY.QUERY_CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return JsonQuery.JSON_QUERY.QUERY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getJsonText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getQueryCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getQueryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JsonQueryRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JsonQueryRecord value2(String value) {
		setJsonText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JsonQueryRecord value3(Timestamp value) {
		setQueryCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JsonQueryRecord value4(Integer value) {
		setQueryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JsonQueryRecord values(Integer value1, String value2, Timestamp value3, Integer value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached JsonQueryRecord
	 */
	public JsonQueryRecord() {
		super(JsonQuery.JSON_QUERY);
	}

	/**
	 * Create a detached, initialised JsonQueryRecord
	 */
	public JsonQueryRecord(Integer id, String jsonText, Timestamp queryCreateTime, Integer queryId) {
		super(JsonQuery.JSON_QUERY);

		setValue(0, id);
		setValue(1, jsonText);
		setValue(2, queryCreateTime);
		setValue(3, queryId);
	}
}
