/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.records;


import de.samply.bbmri.negotiator.jooq.tables.NetworkBiobankLink;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NetworkBiobankLinkRecord extends TableRecordImpl<NetworkBiobankLinkRecord> implements Record2<Integer, Integer> {

	private static final long serialVersionUID = -1347276662;

	/**
	 * Setter for <code>public.network_biobank_link.biobank_id</code>.
	 */
	public void setBiobankId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.network_biobank_link.biobank_id</code>.
	 */
	public Integer getBiobankId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.network_biobank_link.network_id</code>.
	 */
	public void setNetworkId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.network_biobank_link.network_id</code>.
	 */
	public Integer getNetworkId() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return NetworkBiobankLink.NETWORK_BIOBANK_LINK.BIOBANK_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return NetworkBiobankLink.NETWORK_BIOBANK_LINK.NETWORK_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getBiobankId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getNetworkId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NetworkBiobankLinkRecord value1(Integer value) {
		setBiobankId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NetworkBiobankLinkRecord value2(Integer value) {
		setNetworkId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NetworkBiobankLinkRecord values(Integer value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NetworkBiobankLinkRecord
	 */
	public NetworkBiobankLinkRecord() {
		super(NetworkBiobankLink.NETWORK_BIOBANK_LINK);
	}

	/**
	 * Create a detached, initialised NetworkBiobankLinkRecord
	 */
	public NetworkBiobankLinkRecord(Integer biobankId, Integer networkId) {
		super(NetworkBiobankLink.NETWORK_BIOBANK_LINK);

		setValue(0, biobankId);
		setValue(1, networkId);
	}
}
