/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.records;


import de.samply.bbmri.negotiator.jooq.tables.QueryAttachmentPrivate;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueryAttachmentPrivateRecord extends UpdatableRecordImpl<QueryAttachmentPrivateRecord> implements Record8<Integer, Integer, Integer, Integer, Timestamp, String, String, Integer> {

	private static final long serialVersionUID = 659403465;

	/**
	 * Setter for <code>public.query_attachment_private.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.query_attachment_private.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.query_attachment_private.query_id</code>.
	 */
	public void setQueryId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.query_attachment_private.query_id</code>.
	 */
	public Integer getQueryId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.query_attachment_private.person_id</code>.
	 */
	public void setPersonId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.query_attachment_private.person_id</code>.
	 */
	public Integer getPersonId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.query_attachment_private.biobank_in_private_chat</code>.
	 */
	public void setBiobankInPrivateChat(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.query_attachment_private.biobank_in_private_chat</code>.
	 */
	public Integer getBiobankInPrivateChat() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.query_attachment_private.attachment_time</code>.
	 */
	public void setAttachmentTime(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.query_attachment_private.attachment_time</code>.
	 */
	public Timestamp getAttachmentTime() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>public.query_attachment_private.attachment</code>.
	 */
	public void setAttachment(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.query_attachment_private.attachment</code>.
	 */
	public String getAttachment() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>public.query_attachment_private.file_type</code>.
	 */
	public void setFileType(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.query_attachment_private.file_type</code>.
	 */
	public String getFileType() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>public.query_attachment_private.offer_id</code>.
	 */
	public void setOfferId(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.query_attachment_private.offer_id</code>.
	 */
	public Integer getOfferId() {
		return (Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Integer, Integer, Timestamp, String, String, Integer> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Integer, Integer, Timestamp, String, String, Integer> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return QueryAttachmentPrivate.QUERY_ATTACHMENT_PRIVATE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return QueryAttachmentPrivate.QUERY_ATTACHMENT_PRIVATE.QUERY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return QueryAttachmentPrivate.QUERY_ATTACHMENT_PRIVATE.PERSON_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return QueryAttachmentPrivate.QUERY_ATTACHMENT_PRIVATE.BIOBANK_IN_PRIVATE_CHAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return QueryAttachmentPrivate.QUERY_ATTACHMENT_PRIVATE.ATTACHMENT_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return QueryAttachmentPrivate.QUERY_ATTACHMENT_PRIVATE.ATTACHMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return QueryAttachmentPrivate.QUERY_ATTACHMENT_PRIVATE.FILE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return QueryAttachmentPrivate.QUERY_ATTACHMENT_PRIVATE.OFFER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getQueryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getPersonId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getBiobankInPrivateChat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getAttachmentTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getAttachment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getFileType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getOfferId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryAttachmentPrivateRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryAttachmentPrivateRecord value2(Integer value) {
		setQueryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryAttachmentPrivateRecord value3(Integer value) {
		setPersonId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryAttachmentPrivateRecord value4(Integer value) {
		setBiobankInPrivateChat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryAttachmentPrivateRecord value5(Timestamp value) {
		setAttachmentTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryAttachmentPrivateRecord value6(String value) {
		setAttachment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryAttachmentPrivateRecord value7(String value) {
		setFileType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryAttachmentPrivateRecord value8(Integer value) {
		setOfferId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryAttachmentPrivateRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Timestamp value5, String value6, String value7, Integer value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached QueryAttachmentPrivateRecord
	 */
	public QueryAttachmentPrivateRecord() {
		super(QueryAttachmentPrivate.QUERY_ATTACHMENT_PRIVATE);
	}

	/**
	 * Create a detached, initialised QueryAttachmentPrivateRecord
	 */
	public QueryAttachmentPrivateRecord(Integer id, Integer queryId, Integer personId, Integer biobankInPrivateChat, Timestamp attachmentTime, String attachment, String fileType, Integer offerId) {
		super(QueryAttachmentPrivate.QUERY_ATTACHMENT_PRIVATE);

		setValue(0, id);
		setValue(1, queryId);
		setValue(2, personId);
		setValue(3, biobankInPrivateChat);
		setValue(4, attachmentTime);
		setValue(5, attachment);
		setValue(6, fileType);
		setValue(7, offerId);
	}
}
