/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.records;


import de.samply.bbmri.negotiator.jooq.tables.QueryAttachment;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Table for queries that have one or more attachments uploaded.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueryAttachmentRecord extends UpdatableRecordImpl<QueryAttachmentRecord> implements Record3<Integer, Integer, String> {

	private static final long serialVersionUID = 893539221;

	/**
	 * Setter for <code>public.query_attachment.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.query_attachment.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.query_attachment.query_id</code>. This column is a foreign key here, taken from query table
	 */
	public void setQueryId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.query_attachment.query_id</code>. This column is a foreign key here, taken from query table
	 */
	public Integer getQueryId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.query_attachment.attachment</code>.
	 */
	public void setAttachment(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.query_attachment.attachment</code>.
	 */
	public String getAttachment() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return QueryAttachment.QUERY_ATTACHMENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return QueryAttachment.QUERY_ATTACHMENT.QUERY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return QueryAttachment.QUERY_ATTACHMENT.ATTACHMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getQueryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getAttachment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryAttachmentRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryAttachmentRecord value2(Integer value) {
		setQueryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryAttachmentRecord value3(String value) {
		setAttachment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryAttachmentRecord values(Integer value1, Integer value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached QueryAttachmentRecord
	 */
	public QueryAttachmentRecord() {
		super(QueryAttachment.QUERY_ATTACHMENT);
	}

	/**
	 * Create a detached, initialised QueryAttachmentRecord
	 */
	public QueryAttachmentRecord(Integer id, Integer queryId, String attachment) {
		super(QueryAttachment.QUERY_ATTACHMENT);

		setValue(0, id);
		setValue(1, queryId);
		setValue(2, attachment);
	}
}
