/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.records;


import de.samply.bbmri.negotiator.jooq.tables.QueryLifecycleCollection;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueryLifecycleCollectionRecord extends TableRecordImpl<QueryLifecycleCollectionRecord> implements Record5<Integer, Integer, Integer, String, Timestamp> {

	private static final long serialVersionUID = 826604306;

	/**
	 * Setter for <code>public.query_lifecycle_collection.query_id</code>.
	 */
	public void setQueryId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.query_lifecycle_collection.query_id</code>.
	 */
	public Integer getQueryId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.query_lifecycle_collection.person_id</code>.
	 */
	public void setPersonId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.query_lifecycle_collection.person_id</code>.
	 */
	public Integer getPersonId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.query_lifecycle_collection.collection_id</code>.
	 */
	public void setCollectionId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.query_lifecycle_collection.collection_id</code>.
	 */
	public Integer getCollectionId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.query_lifecycle_collection.status</code>.
	 */
	public void setStatus(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.query_lifecycle_collection.status</code>.
	 */
	public String getStatus() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.query_lifecycle_collection.lifecycle_time</code>.
	 */
	public void setLifecycleTime(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.query_lifecycle_collection.lifecycle_time</code>.
	 */
	public Timestamp getLifecycleTime() {
		return (Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, Integer, String, Timestamp> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, Integer, String, Timestamp> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return QueryLifecycleCollection.QUERY_LIFECYCLE_COLLECTION.QUERY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return QueryLifecycleCollection.QUERY_LIFECYCLE_COLLECTION.PERSON_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return QueryLifecycleCollection.QUERY_LIFECYCLE_COLLECTION.COLLECTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return QueryLifecycleCollection.QUERY_LIFECYCLE_COLLECTION.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return QueryLifecycleCollection.QUERY_LIFECYCLE_COLLECTION.LIFECYCLE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getQueryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getPersonId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getCollectionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getLifecycleTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryLifecycleCollectionRecord value1(Integer value) {
		setQueryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryLifecycleCollectionRecord value2(Integer value) {
		setPersonId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryLifecycleCollectionRecord value3(Integer value) {
		setCollectionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryLifecycleCollectionRecord value4(String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryLifecycleCollectionRecord value5(Timestamp value) {
		setLifecycleTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryLifecycleCollectionRecord values(Integer value1, Integer value2, Integer value3, String value4, Timestamp value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached QueryLifecycleCollectionRecord
	 */
	public QueryLifecycleCollectionRecord() {
		super(QueryLifecycleCollection.QUERY_LIFECYCLE_COLLECTION);
	}

	/**
	 * Create a detached, initialised QueryLifecycleCollectionRecord
	 */
	public QueryLifecycleCollectionRecord(Integer queryId, Integer personId, Integer collectionId, String status, Timestamp lifecycleTime) {
		super(QueryLifecycleCollection.QUERY_LIFECYCLE_COLLECTION);

		setValue(0, queryId);
		setValue(1, personId);
		setValue(2, collectionId);
		setValue(3, status);
		setValue(4, lifecycleTime);
	}
}
