/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.records;


import de.samply.bbmri.negotiator.jooq.tables.QueryLifecycleCollection;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueryLifecycleCollectionRecord extends UpdatableRecordImpl<QueryLifecycleCollectionRecord> implements Record8<Integer, Integer, Integer, String, Timestamp, Integer, String, String> {

	private static final long serialVersionUID = -658915686;

	/**
	 * Setter for <code>public.query_lifecycle_collection.query_id</code>.
	 */
	public void setQueryId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.query_lifecycle_collection.query_id</code>.
	 */
	public Integer getQueryId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.query_lifecycle_collection.status_user_id</code>.
	 */
	public void setStatusUserId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.query_lifecycle_collection.status_user_id</code>.
	 */
	public Integer getStatusUserId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.query_lifecycle_collection.collection_id</code>.
	 */
	public void setCollectionId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.query_lifecycle_collection.collection_id</code>.
	 */
	public Integer getCollectionId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.query_lifecycle_collection.status</code>.
	 */
	public void setStatus(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.query_lifecycle_collection.status</code>.
	 */
	public String getStatus() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.query_lifecycle_collection.status_date</code>.
	 */
	public void setStatusDate(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.query_lifecycle_collection.status_date</code>.
	 */
	public Timestamp getStatusDate() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>public.query_lifecycle_collection.id</code>.
	 */
	public void setId(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.query_lifecycle_collection.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>public.query_lifecycle_collection.status_type</code>.
	 */
	public void setStatusType(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.query_lifecycle_collection.status_type</code>.
	 */
	public String getStatusType() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>public.query_lifecycle_collection.status_json</code>.
	 */
	public void setStatusJson(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.query_lifecycle_collection.status_json</code>.
	 */
	public String getStatusJson() {
		return (String) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Integer, String, Timestamp, Integer, String, String> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Integer, String, Timestamp, Integer, String, String> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return QueryLifecycleCollection.QUERY_LIFECYCLE_COLLECTION.QUERY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return QueryLifecycleCollection.QUERY_LIFECYCLE_COLLECTION.STATUS_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return QueryLifecycleCollection.QUERY_LIFECYCLE_COLLECTION.COLLECTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return QueryLifecycleCollection.QUERY_LIFECYCLE_COLLECTION.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return QueryLifecycleCollection.QUERY_LIFECYCLE_COLLECTION.STATUS_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return QueryLifecycleCollection.QUERY_LIFECYCLE_COLLECTION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return QueryLifecycleCollection.QUERY_LIFECYCLE_COLLECTION.STATUS_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return QueryLifecycleCollection.QUERY_LIFECYCLE_COLLECTION.STATUS_JSON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getQueryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getStatusUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getCollectionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getStatusDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getStatusType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getStatusJson();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryLifecycleCollectionRecord value1(Integer value) {
		setQueryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryLifecycleCollectionRecord value2(Integer value) {
		setStatusUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryLifecycleCollectionRecord value3(Integer value) {
		setCollectionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryLifecycleCollectionRecord value4(String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryLifecycleCollectionRecord value5(Timestamp value) {
		setStatusDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryLifecycleCollectionRecord value6(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryLifecycleCollectionRecord value7(String value) {
		setStatusType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryLifecycleCollectionRecord value8(String value) {
		setStatusJson(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QueryLifecycleCollectionRecord values(Integer value1, Integer value2, Integer value3, String value4, Timestamp value5, Integer value6, String value7, String value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached QueryLifecycleCollectionRecord
	 */
	public QueryLifecycleCollectionRecord() {
		super(QueryLifecycleCollection.QUERY_LIFECYCLE_COLLECTION);
	}

	/**
	 * Create a detached, initialised QueryLifecycleCollectionRecord
	 */
	public QueryLifecycleCollectionRecord(Integer queryId, Integer statusUserId, Integer collectionId, String status, Timestamp statusDate, Integer id, String statusType, String statusJson) {
		super(QueryLifecycleCollection.QUERY_LIFECYCLE_COLLECTION);

		setValue(0, queryId);
		setValue(1, statusUserId);
		setValue(2, collectionId);
		setValue(3, status);
		setValue(4, statusDate);
		setValue(5, id);
		setValue(6, statusType);
		setValue(7, statusJson);
	}
}
