/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.JOOQ.tables.daos;


import de.samply.bbmri.negotiator.JOOQ.tables.Comment;
import de.samply.bbmri.negotiator.JOOQ.tables.records.CommentRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * table to store comments on a query
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentDao extends DAOImpl<CommentRecord, de.samply.bbmri.negotiator.JOOQ.tables.pojos.Comment, Integer> {

	/**
	 * Create a new CommentDao without any configuration
	 */
	public CommentDao() {
		super(Comment.COMMENT, de.samply.bbmri.negotiator.JOOQ.tables.pojos.Comment.class);
	}

	/**
	 * Create a new CommentDao with an attached configuration
	 */
	public CommentDao(Configuration configuration) {
		super(Comment.COMMENT, de.samply.bbmri.negotiator.JOOQ.tables.pojos.Comment.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(de.samply.bbmri.negotiator.JOOQ.tables.pojos.Comment object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.JOOQ.tables.pojos.Comment> fetchById(Integer... values) {
		return fetch(Comment.COMMENT.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public de.samply.bbmri.negotiator.JOOQ.tables.pojos.Comment fetchOneById(Integer value) {
		return fetchOne(Comment.COMMENT.ID, value);
	}

	/**
	 * Fetch records that have <code>queryId IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.JOOQ.tables.pojos.Comment> fetchByQueryid(Integer... values) {
		return fetch(Comment.COMMENT.QUERYID, values);
	}

	/**
	 * Fetch records that have <code>timeStamp IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.JOOQ.tables.pojos.Comment> fetchByTimestamp(Timestamp... values) {
		return fetch(Comment.COMMENT.TIMESTAMP, values);
	}

	/**
	 * Fetch records that have <code>personId IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.JOOQ.tables.pojos.Comment> fetchByPersonid(Integer... values) {
		return fetch(Comment.COMMENT.PERSONID, values);
	}

	/**
	 * Fetch records that have <code>text IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.JOOQ.tables.pojos.Comment> fetchByText(String... values) {
		return fetch(Comment.COMMENT.TEXT, values);
	}
}
