/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.daos;


import de.samply.bbmri.negotiator.jooq.enums.Flag;
import de.samply.bbmri.negotiator.jooq.tables.FlaggedQuery;
import de.samply.bbmri.negotiator.jooq.tables.records.FlaggedQueryRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * Table for queries that are flagged/bookmarked. bookmark options are starred, 
 * archived and ignored.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlaggedQueryDao extends DAOImpl<FlaggedQueryRecord, de.samply.bbmri.negotiator.jooq.tables.pojos.FlaggedQuery, Record2<Integer, Integer>> {

	/**
	 * Create a new FlaggedQueryDao without any configuration
	 */
	public FlaggedQueryDao() {
		super(FlaggedQuery.FLAGGED_QUERY, de.samply.bbmri.negotiator.jooq.tables.pojos.FlaggedQuery.class);
	}

	/**
	 * Create a new FlaggedQueryDao with an attached configuration
	 */
	public FlaggedQueryDao(Configuration configuration) {
		super(FlaggedQuery.FLAGGED_QUERY, de.samply.bbmri.negotiator.jooq.tables.pojos.FlaggedQuery.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Record2<Integer, Integer> getId(de.samply.bbmri.negotiator.jooq.tables.pojos.FlaggedQuery object) {
		return compositeKeyRecord(object.getQueryId(), object.getPersonId());
	}

	/**
	 * Fetch records that have <code>query_id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.FlaggedQuery> fetchByQueryId(Integer... values) {
		return fetch(FlaggedQuery.FLAGGED_QUERY.QUERY_ID, values);
	}

	/**
	 * Fetch records that have <code>person_id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.FlaggedQuery> fetchByPersonId(Integer... values) {
		return fetch(FlaggedQuery.FLAGGED_QUERY.PERSON_ID, values);
	}

	/**
	 * Fetch records that have <code>flag IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.FlaggedQuery> fetchByFlag(Flag... values) {
		return fetch(FlaggedQuery.FLAGGED_QUERY.FLAG, values);
	}
}
