/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.daos;


import de.samply.bbmri.negotiator.jooq.tables.ModeratorNetwork;
import de.samply.bbmri.negotiator.jooq.tables.records.ModeratorNetworkRecord;
import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;

import javax.annotation.Generated;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModeratorNetworkDao extends DAOImpl<ModeratorNetworkRecord, de.samply.bbmri.negotiator.jooq.tables.pojos.ModeratorNetwork, Record2<Integer, Integer>> {

	/**
	 * Create a new ModeratorNetworkDao without any configuration
	 */
	public ModeratorNetworkDao() {
		super(ModeratorNetwork.MODERATOR_NETWORK, de.samply.bbmri.negotiator.jooq.tables.pojos.ModeratorNetwork.class);
	}

	/**
	 * Create a new ModeratorNetworkDao with an attached configuration
	 */
	public ModeratorNetworkDao(Configuration configuration) {
		super(ModeratorNetwork.MODERATOR_NETWORK, de.samply.bbmri.negotiator.jooq.tables.pojos.ModeratorNetwork.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Record2<Integer, Integer> getId(de.samply.bbmri.negotiator.jooq.tables.pojos.ModeratorNetwork object) {
		return compositeKeyRecord(object.getPersonId(), object.getNetworkId());
	}

	/**
	 * Fetch records that have <code>person_id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.ModeratorNetwork> fetchByPersonId(Integer... values) {
		return fetch(ModeratorNetwork.MODERATOR_NETWORK.PERSON_ID, values);
	}

	/**
	 * Fetch records that have <code>network_id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.ModeratorNetwork> fetchByNetworkId(Integer... values) {
		return fetch(ModeratorNetwork.MODERATOR_NETWORK.NETWORK_ID, values);
	}
}
