/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.daos;


import de.samply.bbmri.negotiator.jooq.tables.NetworkCollectionLink;
import de.samply.bbmri.negotiator.jooq.tables.records.NetworkCollectionLinkRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NetworkCollectionLinkDao extends DAOImpl<NetworkCollectionLinkRecord, de.samply.bbmri.negotiator.jooq.tables.pojos.NetworkCollectionLink, Record2<Integer, Integer>> {

	/**
	 * Create a new NetworkCollectionLinkDao without any configuration
	 */
	public NetworkCollectionLinkDao() {
		super(NetworkCollectionLink.NETWORK_COLLECTION_LINK, de.samply.bbmri.negotiator.jooq.tables.pojos.NetworkCollectionLink.class);
	}

	/**
	 * Create a new NetworkCollectionLinkDao with an attached configuration
	 */
	public NetworkCollectionLinkDao(Configuration configuration) {
		super(NetworkCollectionLink.NETWORK_COLLECTION_LINK, de.samply.bbmri.negotiator.jooq.tables.pojos.NetworkCollectionLink.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Record2<Integer, Integer> getId(de.samply.bbmri.negotiator.jooq.tables.pojos.NetworkCollectionLink object) {
		return compositeKeyRecord(object.getCollectionId(), object.getNetworkId());
	}

	/**
	 * Fetch records that have <code>collection_id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.NetworkCollectionLink> fetchByCollectionId(Integer... values) {
		return fetch(NetworkCollectionLink.NETWORK_COLLECTION_LINK.COLLECTION_ID, values);
	}

	/**
	 * Fetch records that have <code>network_id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.NetworkCollectionLink> fetchByNetworkId(Integer... values) {
		return fetch(NetworkCollectionLink.NETWORK_COLLECTION_LINK.NETWORK_ID, values);
	}
}
