/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.daos;


import de.samply.bbmri.negotiator.jooq.tables.Network;
import de.samply.bbmri.negotiator.jooq.tables.records.NetworkRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NetworkDao extends DAOImpl<NetworkRecord, de.samply.bbmri.negotiator.jooq.tables.pojos.Network, Integer> {

	/**
	 * Create a new NetworkDao without any configuration
	 */
	public NetworkDao() {
		super(Network.NETWORK, de.samply.bbmri.negotiator.jooq.tables.pojos.Network.class);
	}

	/**
	 * Create a new NetworkDao with an attached configuration
	 */
	public NetworkDao(Configuration configuration) {
		super(Network.NETWORK, de.samply.bbmri.negotiator.jooq.tables.pojos.Network.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(de.samply.bbmri.negotiator.jooq.tables.pojos.Network object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.Network> fetchById(Integer... values) {
		return fetch(Network.NETWORK.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public de.samply.bbmri.negotiator.jooq.tables.pojos.Network fetchOneById(Integer value) {
		return fetchOne(Network.NETWORK.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.Network> fetchByName(String... values) {
		return fetch(Network.NETWORK.NAME, values);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.Network> fetchByDescription(String... values) {
		return fetch(Network.NETWORK.DESCRIPTION, values);
	}

	/**
	 * Fetch records that have <code>acronym IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.Network> fetchByAcronym(String... values) {
		return fetch(Network.NETWORK.ACRONYM, values);
	}

	/**
	 * Fetch records that have <code>directory_id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.Network> fetchByDirectoryId(String... values) {
		return fetch(Network.NETWORK.DIRECTORY_ID, values);
	}

	/**
	 * Fetch records that have <code>list_of_directories_id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.Network> fetchByListOfDirectoriesId(Integer... values) {
		return fetch(Network.NETWORK.LIST_OF_DIRECTORIES_ID, values);
	}
}
