/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.daos;


import de.samply.bbmri.negotiator.jooq.tables.NotificationSetting;
import de.samply.bbmri.negotiator.jooq.tables.records.NotificationSettingRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationSettingDao extends DAOImpl<NotificationSettingRecord, de.samply.bbmri.negotiator.jooq.tables.pojos.NotificationSetting, Integer> {

	/**
	 * Create a new NotificationSettingDao without any configuration
	 */
	public NotificationSettingDao() {
		super(NotificationSetting.NOTIFICATION_SETTING, de.samply.bbmri.negotiator.jooq.tables.pojos.NotificationSetting.class);
	}

	/**
	 * Create a new NotificationSettingDao with an attached configuration
	 */
	public NotificationSettingDao(Configuration configuration) {
		super(NotificationSetting.NOTIFICATION_SETTING, de.samply.bbmri.negotiator.jooq.tables.pojos.NotificationSetting.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(de.samply.bbmri.negotiator.jooq.tables.pojos.NotificationSetting object) {
		return object.getNotificationSettingId();
	}

	/**
	 * Fetch records that have <code>notification_setting_id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.NotificationSetting> fetchByNotificationSettingId(Integer... values) {
		return fetch(NotificationSetting.NOTIFICATION_SETTING.NOTIFICATION_SETTING_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>notification_setting_id = value</code>
	 */
	public de.samply.bbmri.negotiator.jooq.tables.pojos.NotificationSetting fetchOneByNotificationSettingId(Integer value) {
		return fetchOne(NotificationSetting.NOTIFICATION_SETTING.NOTIFICATION_SETTING_ID, value);
	}

	/**
	 * Fetch records that have <code>person_id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.NotificationSetting> fetchByPersonId(Integer... values) {
		return fetch(NotificationSetting.NOTIFICATION_SETTING.PERSON_ID, values);
	}

	/**
	 * Fetch records that have <code>notification_type IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.NotificationSetting> fetchByNotificationType(String... values) {
		return fetch(NotificationSetting.NOTIFICATION_SETTING.NOTIFICATION_TYPE, values);
	}

	/**
	 * Fetch records that have <code>send_settings IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.NotificationSetting> fetchBySendSettings(String... values) {
		return fetch(NotificationSetting.NOTIFICATION_SETTING.SEND_SETTINGS, values);
	}
}
