/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.daos;


import de.samply.bbmri.negotiator.jooq.tables.Notification;
import de.samply.bbmri.negotiator.jooq.tables.records.NotificationRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationDao extends DAOImpl<NotificationRecord, de.samply.bbmri.negotiator.jooq.tables.pojos.Notification, Integer> {

	/**
	 * Create a new NotificationDao without any configuration
	 */
	public NotificationDao() {
		super(Notification.NOTIFICATION, de.samply.bbmri.negotiator.jooq.tables.pojos.Notification.class);
	}

	/**
	 * Create a new NotificationDao with an attached configuration
	 */
	public NotificationDao(Configuration configuration) {
		super(Notification.NOTIFICATION, de.samply.bbmri.negotiator.jooq.tables.pojos.Notification.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(de.samply.bbmri.negotiator.jooq.tables.pojos.Notification object) {
		return object.getNotificationId();
	}

	/**
	 * Fetch records that have <code>notification_id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.Notification> fetchByNotificationId(Integer... values) {
		return fetch(Notification.NOTIFICATION.NOTIFICATION_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>notification_id = value</code>
	 */
	public de.samply.bbmri.negotiator.jooq.tables.pojos.Notification fetchOneByNotificationId(Integer value) {
		return fetchOne(Notification.NOTIFICATION.NOTIFICATION_ID, value);
	}

	/**
	 * Fetch records that have <code>query_id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.Notification> fetchByQueryId(Integer... values) {
		return fetch(Notification.NOTIFICATION.QUERY_ID, values);
	}

	/**
	 * Fetch records that have <code>comment_id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.Notification> fetchByCommentId(Integer... values) {
		return fetch(Notification.NOTIFICATION.COMMENT_ID, values);
	}

	/**
	 * Fetch records that have <code>person_id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.Notification> fetchByPersonId(Integer... values) {
		return fetch(Notification.NOTIFICATION.PERSON_ID, values);
	}

	/**
	 * Fetch records that have <code>notification_type IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.Notification> fetchByNotificationType(String... values) {
		return fetch(Notification.NOTIFICATION.NOTIFICATION_TYPE, values);
	}

	/**
	 * Fetch records that have <code>create_date IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.Notification> fetchByCreateDate(Timestamp... values) {
		return fetch(Notification.NOTIFICATION.CREATE_DATE, values);
	}
}
