/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.daos;


import de.samply.bbmri.negotiator.jooq.tables.QueryAttachmentComment;
import de.samply.bbmri.negotiator.jooq.tables.records.QueryAttachmentCommentRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * Table for queries that have one or more attachments uploaded.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueryAttachmentCommentDao extends DAOImpl<QueryAttachmentCommentRecord, de.samply.bbmri.negotiator.jooq.tables.pojos.QueryAttachmentComment, Integer> {

	/**
	 * Create a new QueryAttachmentCommentDao without any configuration
	 */
	public QueryAttachmentCommentDao() {
		super(QueryAttachmentComment.QUERY_ATTACHMENT_COMMENT, de.samply.bbmri.negotiator.jooq.tables.pojos.QueryAttachmentComment.class);
	}

	/**
	 * Create a new QueryAttachmentCommentDao with an attached configuration
	 */
	public QueryAttachmentCommentDao(Configuration configuration) {
		super(QueryAttachmentComment.QUERY_ATTACHMENT_COMMENT, de.samply.bbmri.negotiator.jooq.tables.pojos.QueryAttachmentComment.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(de.samply.bbmri.negotiator.jooq.tables.pojos.QueryAttachmentComment object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.QueryAttachmentComment> fetchById(Integer... values) {
		return fetch(QueryAttachmentComment.QUERY_ATTACHMENT_COMMENT.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public de.samply.bbmri.negotiator.jooq.tables.pojos.QueryAttachmentComment fetchOneById(Integer value) {
		return fetchOne(QueryAttachmentComment.QUERY_ATTACHMENT_COMMENT.ID, value);
	}

	/**
	 * Fetch records that have <code>query_id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.QueryAttachmentComment> fetchByQueryId(Integer... values) {
		return fetch(QueryAttachmentComment.QUERY_ATTACHMENT_COMMENT.QUERY_ID, values);
	}

	/**
	 * Fetch records that have <code>attachment IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.QueryAttachmentComment> fetchByAttachment(String... values) {
		return fetch(QueryAttachmentComment.QUERY_ATTACHMENT_COMMENT.ATTACHMENT, values);
	}

	/**
	 * Fetch records that have <code>attachment_type IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.QueryAttachmentComment> fetchByAttachmentType(String... values) {
		return fetch(QueryAttachmentComment.QUERY_ATTACHMENT_COMMENT.ATTACHMENT_TYPE, values);
	}

	/**
	 * Fetch records that have <code>comment_id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.QueryAttachmentComment> fetchByCommentId(Integer... values) {
		return fetch(QueryAttachmentComment.QUERY_ATTACHMENT_COMMENT.COMMENT_ID, values);
	}
}
