/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.daos;


import de.samply.bbmri.negotiator.jooq.tables.QueryLocation;
import de.samply.bbmri.negotiator.jooq.tables.records.QueryLocationRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * Table for all the locations that have replied to a query.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueryLocationDao extends DAOImpl<QueryLocationRecord, de.samply.bbmri.negotiator.jooq.tables.pojos.QueryLocation, Record2<Integer, Integer>> {

	/**
	 * Create a new QueryLocationDao without any configuration
	 */
	public QueryLocationDao() {
		super(QueryLocation.QUERY_LOCATION, de.samply.bbmri.negotiator.jooq.tables.pojos.QueryLocation.class);
	}

	/**
	 * Create a new QueryLocationDao with an attached configuration
	 */
	public QueryLocationDao(Configuration configuration) {
		super(QueryLocation.QUERY_LOCATION, de.samply.bbmri.negotiator.jooq.tables.pojos.QueryLocation.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Record2<Integer, Integer> getId(de.samply.bbmri.negotiator.jooq.tables.pojos.QueryLocation object) {
		return compositeKeyRecord(object.getQueryId(), object.getLocationId());
	}

	/**
	 * Fetch records that have <code>query_id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.QueryLocation> fetchByQueryId(Integer... values) {
		return fetch(QueryLocation.QUERY_LOCATION.QUERY_ID, values);
	}

	/**
	 * Fetch records that have <code>location_id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.QueryLocation> fetchByLocationId(Integer... values) {
		return fetch(QueryLocation.QUERY_LOCATION.LOCATION_ID, values);
	}
}
