/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.daos;


import de.samply.bbmri.negotiator.jooq.tables.Researcher;
import de.samply.bbmri.negotiator.jooq.tables.records.ResearcherRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * researcher table - one of the child's of the person table 
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResearcherDao extends DAOImpl<ResearcherRecord, de.samply.bbmri.negotiator.jooq.tables.pojos.Researcher, Integer> {

	/**
	 * Create a new ResearcherDao without any configuration
	 */
	public ResearcherDao() {
		super(Researcher.RESEARCHER, de.samply.bbmri.negotiator.jooq.tables.pojos.Researcher.class);
	}

	/**
	 * Create a new ResearcherDao with an attached configuration
	 */
	public ResearcherDao(Configuration configuration) {
		super(Researcher.RESEARCHER, de.samply.bbmri.negotiator.jooq.tables.pojos.Researcher.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(de.samply.bbmri.negotiator.jooq.tables.pojos.Researcher object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<de.samply.bbmri.negotiator.jooq.tables.pojos.Researcher> fetchById(Integer... values) {
		return fetch(Researcher.RESEARCHER.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public de.samply.bbmri.negotiator.jooq.tables.pojos.Researcher fetchOneById(Integer value) {
		return fetchOne(Researcher.RESEARCHER.ID, value);
	}
}
