#!/bin/bash

if [ $# -ne 2 ]; then
  echo 1>&2 "Usage: $0 username password"
  exit 3
fi


export username=$1
export PGPASSWORD=$2

echo dropping database
dropdb -U $username -h localhost negotiator

echo creating database
createdb -U $username -h localhost negotiator

psql -U $username -d negotiator -a -f ./src/main/resources/sql/database.sql
psql -U $username -d negotiator -a -f ./src/main/resources/sql/dummyData.sql