/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq;


import de.samply.bbmri.negotiator.jooq.tables.Comment;
import de.samply.bbmri.negotiator.jooq.tables.Flaggedquery;
import de.samply.bbmri.negotiator.jooq.tables.Location;
import de.samply.bbmri.negotiator.jooq.tables.Person;
import de.samply.bbmri.negotiator.jooq.tables.Query;
import de.samply.bbmri.negotiator.jooq.tables.Tag;
import de.samply.bbmri.negotiator.jooq.tables.Taggedquery;
import de.samply.bbmri.negotiator.jooq.tables.records.CommentRecord;
import de.samply.bbmri.negotiator.jooq.tables.records.FlaggedqueryRecord;
import de.samply.bbmri.negotiator.jooq.tables.records.LocationRecord;
import de.samply.bbmri.negotiator.jooq.tables.records.PersonRecord;
import de.samply.bbmri.negotiator.jooq.tables.records.QueryRecord;
import de.samply.bbmri.negotiator.jooq.tables.records.TagRecord;
import de.samply.bbmri.negotiator.jooq.tables.records.TaggedqueryRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<CommentRecord, Integer> IDENTITY_COMMENT = Identities0.IDENTITY_COMMENT;
	public static final Identity<LocationRecord, Integer> IDENTITY_LOCATION = Identities0.IDENTITY_LOCATION;
	public static final Identity<PersonRecord, Integer> IDENTITY_PERSON = Identities0.IDENTITY_PERSON;
	public static final Identity<QueryRecord, Integer> IDENTITY_QUERY = Identities0.IDENTITY_QUERY;
	public static final Identity<TagRecord, Integer> IDENTITY_TAG = Identities0.IDENTITY_TAG;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<CommentRecord> COMMENT_PKEY = UniqueKeys0.COMMENT_PKEY;
	public static final UniqueKey<FlaggedqueryRecord> FLAGGEDQUERY_PKEY = UniqueKeys0.FLAGGEDQUERY_PKEY;
	public static final UniqueKey<LocationRecord> LOCATION_PKEY = UniqueKeys0.LOCATION_PKEY;
	public static final UniqueKey<PersonRecord> PERSON_PKEY = UniqueKeys0.PERSON_PKEY;
	public static final UniqueKey<QueryRecord> QUERY_PKEY = UniqueKeys0.QUERY_PKEY;
	public static final UniqueKey<TagRecord> TAG_PKEY = UniqueKeys0.TAG_PKEY;
	public static final UniqueKey<TaggedqueryRecord> TAGGEDQUERY_PKEY = UniqueKeys0.TAGGEDQUERY_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<CommentRecord, QueryRecord> COMMENT__COMMENT_QUERYID_FKEY = ForeignKeys0.COMMENT__COMMENT_QUERYID_FKEY;
	public static final ForeignKey<CommentRecord, PersonRecord> COMMENT__COMMENT_PERSONID_FKEY = ForeignKeys0.COMMENT__COMMENT_PERSONID_FKEY;
	public static final ForeignKey<FlaggedqueryRecord, QueryRecord> FLAGGEDQUERY__FLAGGEDQUERY_QUERYID_FKEY = ForeignKeys0.FLAGGEDQUERY__FLAGGEDQUERY_QUERYID_FKEY;
	public static final ForeignKey<FlaggedqueryRecord, PersonRecord> FLAGGEDQUERY__FLAGGEDQUERY_PERSONID_FKEY = ForeignKeys0.FLAGGEDQUERY__FLAGGEDQUERY_PERSONID_FKEY;
	public static final ForeignKey<PersonRecord, LocationRecord> PERSON__PERSON_LOCATIONID_FKEY = ForeignKeys0.PERSON__PERSON_LOCATIONID_FKEY;
	public static final ForeignKey<QueryRecord, PersonRecord> QUERY__QUERY_RESEARCHERID_FKEY = ForeignKeys0.QUERY__QUERY_RESEARCHERID_FKEY;
	public static final ForeignKey<TagRecord, QueryRecord> TAG__TAG_QUERYID_FKEY = ForeignKeys0.TAG__TAG_QUERYID_FKEY;
	public static final ForeignKey<TaggedqueryRecord, QueryRecord> TAGGEDQUERY__TAGGEDQUERY_QUERYID_FKEY = ForeignKeys0.TAGGEDQUERY__TAGGEDQUERY_QUERYID_FKEY;
	public static final ForeignKey<TaggedqueryRecord, TagRecord> TAGGEDQUERY__TAGGEDQUERY_TAGID_FKEY = ForeignKeys0.TAGGEDQUERY__TAGGEDQUERY_TAGID_FKEY;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<CommentRecord, Integer> IDENTITY_COMMENT = createIdentity(Comment.COMMENT, Comment.COMMENT.ID);
		public static Identity<LocationRecord, Integer> IDENTITY_LOCATION = createIdentity(Location.LOCATION, Location.LOCATION.ID);
		public static Identity<PersonRecord, Integer> IDENTITY_PERSON = createIdentity(Person.PERSON, Person.PERSON.ID);
		public static Identity<QueryRecord, Integer> IDENTITY_QUERY = createIdentity(Query.QUERY, Query.QUERY.ID);
		public static Identity<TagRecord, Integer> IDENTITY_TAG = createIdentity(Tag.TAG, Tag.TAG.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<CommentRecord> COMMENT_PKEY = createUniqueKey(Comment.COMMENT, Comment.COMMENT.ID);
		public static final UniqueKey<FlaggedqueryRecord> FLAGGEDQUERY_PKEY = createUniqueKey(Flaggedquery.FLAGGEDQUERY, Flaggedquery.FLAGGEDQUERY.QUERYID, Flaggedquery.FLAGGEDQUERY.PERSONID);
		public static final UniqueKey<LocationRecord> LOCATION_PKEY = createUniqueKey(Location.LOCATION, Location.LOCATION.ID);
		public static final UniqueKey<PersonRecord> PERSON_PKEY = createUniqueKey(Person.PERSON, Person.PERSON.ID);
		public static final UniqueKey<QueryRecord> QUERY_PKEY = createUniqueKey(Query.QUERY, Query.QUERY.ID);
		public static final UniqueKey<TagRecord> TAG_PKEY = createUniqueKey(Tag.TAG, Tag.TAG.ID);
		public static final UniqueKey<TaggedqueryRecord> TAGGEDQUERY_PKEY = createUniqueKey(Taggedquery.TAGGEDQUERY, Taggedquery.TAGGEDQUERY.QUERYID, Taggedquery.TAGGEDQUERY.TAGID);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<CommentRecord, QueryRecord> COMMENT__COMMENT_QUERYID_FKEY = createForeignKey(de.samply.bbmri.negotiator.jooq.Keys.QUERY_PKEY, Comment.COMMENT, Comment.COMMENT.QUERYID);
		public static final ForeignKey<CommentRecord, PersonRecord> COMMENT__COMMENT_PERSONID_FKEY = createForeignKey(de.samply.bbmri.negotiator.jooq.Keys.PERSON_PKEY, Comment.COMMENT, Comment.COMMENT.PERSONID);
		public static final ForeignKey<FlaggedqueryRecord, QueryRecord> FLAGGEDQUERY__FLAGGEDQUERY_QUERYID_FKEY = createForeignKey(de.samply.bbmri.negotiator.jooq.Keys.QUERY_PKEY, Flaggedquery.FLAGGEDQUERY, Flaggedquery.FLAGGEDQUERY.QUERYID);
		public static final ForeignKey<FlaggedqueryRecord, PersonRecord> FLAGGEDQUERY__FLAGGEDQUERY_PERSONID_FKEY = createForeignKey(de.samply.bbmri.negotiator.jooq.Keys.PERSON_PKEY, Flaggedquery.FLAGGEDQUERY, Flaggedquery.FLAGGEDQUERY.PERSONID);
		public static final ForeignKey<PersonRecord, LocationRecord> PERSON__PERSON_LOCATIONID_FKEY = createForeignKey(de.samply.bbmri.negotiator.jooq.Keys.LOCATION_PKEY, Person.PERSON, Person.PERSON.LOCATIONID);
		public static final ForeignKey<QueryRecord, PersonRecord> QUERY__QUERY_RESEARCHERID_FKEY = createForeignKey(de.samply.bbmri.negotiator.jooq.Keys.PERSON_PKEY, Query.QUERY, Query.QUERY.RESEARCHERID);
		public static final ForeignKey<TagRecord, QueryRecord> TAG__TAG_QUERYID_FKEY = createForeignKey(de.samply.bbmri.negotiator.jooq.Keys.QUERY_PKEY, Tag.TAG, Tag.TAG.QUERYID);
		public static final ForeignKey<TaggedqueryRecord, QueryRecord> TAGGEDQUERY__TAGGEDQUERY_QUERYID_FKEY = createForeignKey(de.samply.bbmri.negotiator.jooq.Keys.QUERY_PKEY, Taggedquery.TAGGEDQUERY, Taggedquery.TAGGEDQUERY.QUERYID);
		public static final ForeignKey<TaggedqueryRecord, TagRecord> TAGGEDQUERY__TAGGEDQUERY_TAGID_FKEY = createForeignKey(de.samply.bbmri.negotiator.jooq.Keys.TAG_PKEY, Taggedquery.TAGGEDQUERY, Taggedquery.TAGGEDQUERY.TAGID);
	}
}
