/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.JOOQ;


import de.samply.bbmri.negotiator.JOOQ.tables.Comment;
import de.samply.bbmri.negotiator.JOOQ.tables.Flaggedquery;
import de.samply.bbmri.negotiator.JOOQ.tables.Location;
import de.samply.bbmri.negotiator.JOOQ.tables.Owner;
import de.samply.bbmri.negotiator.JOOQ.tables.Person;
import de.samply.bbmri.negotiator.JOOQ.tables.Query;
import de.samply.bbmri.negotiator.JOOQ.tables.Researcher;
import de.samply.bbmri.negotiator.JOOQ.tables.Tag;
import de.samply.bbmri.negotiator.JOOQ.tables.Taggedquery;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

	private static final long serialVersionUID = -1190709411;

	/**
	 * The reference instance of <code>public</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.COMMENT_ID_SEQ,
			Sequences.COMMENT_PERSONID_SEQ,
			Sequences.COMMENT_QUERYID_SEQ,
			Sequences.FLAGGEDQUERY_OWNERID_SEQ,
			Sequences.FLAGGEDQUERY_QUERYID_SEQ,
			Sequences.LOCATION_ID_SEQ,
			Sequences.OWNER_ID_SEQ,
			Sequences.OWNER_LOCATIONID_SEQ,
			Sequences.PERSON_ID_SEQ,
			Sequences.QUERY_ID_SEQ,
			Sequences.QUERY_RESEARCHERID_SEQ,
			Sequences.RESEARCHER_ID_SEQ,
			Sequences.TAG_ID_SEQ,
			Sequences.TAG_QUERYID_SEQ,
			Sequences.TAGGEDQUERY_QUERYID_SEQ,
			Sequences.TAGGEDQUERY_TAGID_SEQ);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Comment.COMMENT,
			Flaggedquery.FLAGGEDQUERY,
			Location.LOCATION,
			Owner.OWNER,
			Person.PERSON,
			Query.QUERY,
			Researcher.RESEARCHER,
			Tag.TAG,
			Taggedquery.TAGGEDQUERY);
	}
}
