/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.JOOQ;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.comment_id_seq</code>
	 */
	public static final Sequence<Long> COMMENT_ID_SEQ = new SequenceImpl<Long>("comment_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.comment_personId_seq</code>
	 */
	public static final Sequence<Long> COMMENT_PERSONID_SEQ = new SequenceImpl<Long>("comment_personId_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.comment_queryId_seq</code>
	 */
	public static final Sequence<Long> COMMENT_QUERYID_SEQ = new SequenceImpl<Long>("comment_queryId_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.flaggedQuery_ownerId_seq</code>
	 */
	public static final Sequence<Long> FLAGGEDQUERY_OWNERID_SEQ = new SequenceImpl<Long>("flaggedQuery_ownerId_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.flaggedQuery_queryId_seq</code>
	 */
	public static final Sequence<Long> FLAGGEDQUERY_QUERYID_SEQ = new SequenceImpl<Long>("flaggedQuery_queryId_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.location_id_seq</code>
	 */
	public static final Sequence<Long> LOCATION_ID_SEQ = new SequenceImpl<Long>("location_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.owner_id_seq</code>
	 */
	public static final Sequence<Long> OWNER_ID_SEQ = new SequenceImpl<Long>("owner_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.owner_locationId_seq</code>
	 */
	public static final Sequence<Long> OWNER_LOCATIONID_SEQ = new SequenceImpl<Long>("owner_locationId_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.person_id_seq</code>
	 */
	public static final Sequence<Long> PERSON_ID_SEQ = new SequenceImpl<Long>("person_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.query_id_seq</code>
	 */
	public static final Sequence<Long> QUERY_ID_SEQ = new SequenceImpl<Long>("query_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.query_researcherId_seq</code>
	 */
	public static final Sequence<Long> QUERY_RESEARCHERID_SEQ = new SequenceImpl<Long>("query_researcherId_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.researcher_id_seq</code>
	 */
	public static final Sequence<Long> RESEARCHER_ID_SEQ = new SequenceImpl<Long>("researcher_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.tag_id_seq</code>
	 */
	public static final Sequence<Long> TAG_ID_SEQ = new SequenceImpl<Long>("tag_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.tag_queryId_seq</code>
	 */
	public static final Sequence<Long> TAG_QUERYID_SEQ = new SequenceImpl<Long>("tag_queryId_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.taggedQuery_queryId_seq</code>
	 */
	public static final Sequence<Long> TAGGEDQUERY_QUERYID_SEQ = new SequenceImpl<Long>("taggedQuery_queryId_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.taggedQuery_tagId_seq</code>
	 */
	public static final Sequence<Long> TAGGEDQUERY_TAGID_SEQ = new SequenceImpl<Long>("taggedQuery_tagId_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
