# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By


class TestDefaultSuite():
  def setup_method(self, method):
    chrome_options = Options()
    chrome_options.add_argument('--no-sandbox')
    chrome_options.add_argument('--headless')
    chrome_options.add_argument('--remote-debugging-port=9222')
    chrome_options.add_argument('--disable-dev-shm-usage')
    chrome_options.binary_location = "/usr/bin/google-chrome"
    self.driver = webdriver.Chrome(options=chrome_options, executable_path="/usr/local/bin/chromedriver")
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_login(self):
    self.driver.get("http://localhost:8080/dev/chose.xhtml")
    self.driver.find_element(By.NAME, "j_idt89:j_idt97").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".success > td:nth-child(1)")
    assert len(elements) > 0
