/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables;


import de.samply.bbmri.negotiator.jooq.Keys;
import de.samply.bbmri.negotiator.jooq.Public;
import de.samply.bbmri.negotiator.jooq.tables.records.ModeratorNetworkRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModeratorNetwork extends TableImpl<ModeratorNetworkRecord> {

	private static final long serialVersionUID = -1025017713;

	/**
	 * The reference instance of <code>public.moderator_network</code>
	 */
	public static final ModeratorNetwork MODERATOR_NETWORK = new ModeratorNetwork();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ModeratorNetworkRecord> getRecordType() {
		return ModeratorNetworkRecord.class;
	}

	/**
	 * The column <code>public.moderator_network.person_id</code>.
	 */
	public final TableField<ModeratorNetworkRecord, Integer> PERSON_ID = createField("person_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.moderator_network.network_id</code>.
	 */
	public final TableField<ModeratorNetworkRecord, Integer> NETWORK_ID = createField("network_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.moderator_network</code> table reference
	 */
	public ModeratorNetwork() {
		this("moderator_network", null);
	}

	/**
	 * Create an aliased <code>public.moderator_network</code> table reference
	 */
	public ModeratorNetwork(String alias) {
		this(alias, MODERATOR_NETWORK);
	}

	private ModeratorNetwork(String alias, Table<ModeratorNetworkRecord> aliased) {
		this(alias, aliased, null);
	}

	private ModeratorNetwork(String alias, Table<ModeratorNetworkRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ModeratorNetworkRecord> getPrimaryKey() {
		return Keys.MODERATOR_NETWORK_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ModeratorNetworkRecord>> getKeys() {
		return Arrays.<UniqueKey<ModeratorNetworkRecord>>asList(Keys.MODERATOR_NETWORK_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ModeratorNetwork as(String alias) {
		return new ModeratorNetwork(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ModeratorNetwork rename(String name) {
		return new ModeratorNetwork(name, null);
	}
}
