/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables;


import de.samply.bbmri.negotiator.jooq.Keys;
import de.samply.bbmri.negotiator.jooq.Public;
import de.samply.bbmri.negotiator.jooq.tables.records.NetworkCollectionLinkRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NetworkCollectionLink extends TableImpl<NetworkCollectionLinkRecord> {

	private static final long serialVersionUID = 1475018876;

	/**
	 * The reference instance of <code>public.network_collection_link</code>
	 */
	public static final NetworkCollectionLink NETWORK_COLLECTION_LINK = new NetworkCollectionLink();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<NetworkCollectionLinkRecord> getRecordType() {
		return NetworkCollectionLinkRecord.class;
	}

	/**
	 * The column <code>public.network_collection_link.collection_id</code>.
	 */
	public final TableField<NetworkCollectionLinkRecord, Integer> COLLECTION_ID = createField("collection_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.network_collection_link.network_id</code>.
	 */
	public final TableField<NetworkCollectionLinkRecord, Integer> NETWORK_ID = createField("network_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.network_collection_link</code> table reference
	 */
	public NetworkCollectionLink() {
		this("network_collection_link", null);
	}

	/**
	 * Create an aliased <code>public.network_collection_link</code> table reference
	 */
	public NetworkCollectionLink(String alias) {
		this(alias, NETWORK_COLLECTION_LINK);
	}

	private NetworkCollectionLink(String alias, Table<NetworkCollectionLinkRecord> aliased) {
		this(alias, aliased, null);
	}

	private NetworkCollectionLink(String alias, Table<NetworkCollectionLinkRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<NetworkCollectionLinkRecord> getPrimaryKey() {
		return Keys.NETWORK_COLLECTION_LINK_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<NetworkCollectionLinkRecord>> getKeys() {
		return Arrays.<UniqueKey<NetworkCollectionLinkRecord>>asList(Keys.NETWORK_COLLECTION_LINK_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NetworkCollectionLink as(String alias) {
		return new NetworkCollectionLink(alias, this);
	}

	/**
	 * Rename this table
	 */
	public NetworkCollectionLink rename(String name) {
		return new NetworkCollectionLink(name, null);
	}
}
