/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.JOOQ.tables;


import de.samply.bbmri.negotiator.JOOQ.Keys;
import de.samply.bbmri.negotiator.JOOQ.Public;
import de.samply.bbmri.negotiator.JOOQ.tables.records.PersonRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * person table which is parent of researcher and owner
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Person extends TableImpl<PersonRecord> {

	private static final long serialVersionUID = -149143728;

	/**
	 * The reference instance of <code>public.person</code>
	 */
	public static final Person PERSON = new Person();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PersonRecord> getRecordType() {
		return PersonRecord.class;
	}

	/**
	 * The column <code>public.person.id</code>. primary key
	 */
	public final TableField<PersonRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "primary key");

	/**
	 * The column <code>public.person.authData</code>. authentication string that comes from 'samply auth'
	 */
	public final TableField<PersonRecord, String> AUTHDATA = createField("authData", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "authentication string that comes from 'samply auth'");

	/**
	 * The column <code>public.person.personType</code>. describes wether the person is researcher or owner - one of the the two child classes. 
	 */
	public final TableField<PersonRecord, String> PERSONTYPE = createField("personType", org.jooq.impl.SQLDataType.CHAR.length(1).nullable(false), this, "describes wether the person is researcher or owner - one of the the two child classes. ");

	/**
	 * The column <code>public.person.personImage</code>. image/avatar of the person
	 */
	public final TableField<PersonRecord, byte[]> PERSONIMAGE = createField("personImage", org.jooq.impl.SQLDataType.BLOB, this, "image/avatar of the person");

	/**
	 * Create a <code>public.person</code> table reference
	 */
	public Person() {
		this("person", null);
	}

	/**
	 * Create an aliased <code>public.person</code> table reference
	 */
	public Person(String alias) {
		this(alias, PERSON);
	}

	private Person(String alias, Table<PersonRecord> aliased) {
		this(alias, aliased, null);
	}

	private Person(String alias, Table<PersonRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "person table which is parent of researcher and owner");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<PersonRecord, Integer> getIdentity() {
		return Keys.IDENTITY_PERSON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PersonRecord> getPrimaryKey() {
		return Keys.PERSON_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PersonRecord>> getKeys() {
		return Arrays.<UniqueKey<PersonRecord>>asList(Keys.PERSON_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Person as(String alias) {
		return new Person(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Person rename(String name) {
		return new Person(name, null);
	}
}
