/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables;


import de.samply.bbmri.negotiator.jooq.Keys;
import de.samply.bbmri.negotiator.jooq.Public;
import de.samply.bbmri.negotiator.jooq.tables.records.RequestStatusRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RequestStatus extends TableImpl<RequestStatusRecord> {

	private static final long serialVersionUID = -393584718;

	/**
	 * The reference instance of <code>public.request_status</code>
	 */
	public static final RequestStatus REQUEST_STATUS = new RequestStatus();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RequestStatusRecord> getRecordType() {
		return RequestStatusRecord.class;
	}

	/**
	 * The column <code>public.request_status.id</code>.
	 */
	public final TableField<RequestStatusRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.request_status.query_id</code>.
	 */
	public final TableField<RequestStatusRecord, Integer> QUERY_ID = createField("query_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.request_status.status</code>.
	 */
	public final TableField<RequestStatusRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.request_status.status_type</code>.
	 */
	public final TableField<RequestStatusRecord, String> STATUS_TYPE = createField("status_type", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.request_status.status_date</code>.
	 */
	public final TableField<RequestStatusRecord, Timestamp> STATUS_DATE = createField("status_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.request_status.status_user_id</code>.
	 */
	public final TableField<RequestStatusRecord, Integer> STATUS_USER_ID = createField("status_user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.request_status.status_json</code>.
	 */
	public final TableField<RequestStatusRecord, String> STATUS_JSON = createField("status_json", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>public.request_status</code> table reference
	 */
	public RequestStatus() {
		this("request_status", null);
	}

	/**
	 * Create an aliased <code>public.request_status</code> table reference
	 */
	public RequestStatus(String alias) {
		this(alias, REQUEST_STATUS);
	}

	private RequestStatus(String alias, Table<RequestStatusRecord> aliased) {
		this(alias, aliased, null);
	}

	private RequestStatus(String alias, Table<RequestStatusRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<RequestStatusRecord, Integer> getIdentity() {
		return Keys.IDENTITY_REQUEST_STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RequestStatusRecord> getPrimaryKey() {
		return Keys.REQUEST_STATUS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RequestStatusRecord>> getKeys() {
		return Arrays.<UniqueKey<RequestStatusRecord>>asList(Keys.REQUEST_STATUS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequestStatus as(String alias) {
		return new RequestStatus(alias, this);
	}

	/**
	 * Rename this table
	 */
	public RequestStatus rename(String name) {
		return new RequestStatus(name, null);
	}
}
