/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.enums;


import de.samply.bbmri.negotiator.jooq.Public;

import javax.annotation.Generated;

import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Flag implements EnumType {

	UNFLAGGED("UNFLAGGED"),

	ARCHIVED("ARCHIVED"),

	IGNORED("IGNORED"),

	STARRED("STARRED"),

	TEST("TEST");

	private final String literal;

	private Flag(String literal) {
		this.literal = literal;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Schema getSchema() {
		return Public.PUBLIC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getName() {
		return "flag";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getLiteral() {
		return literal;
	}
}
