/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Table to store collections from the directory
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Collection implements Serializable {

	private static final long serialVersionUID = 1324177370;

	private Integer id;
	private String  name;
	private String  directoryId;
	private Integer biobankId;
	private Integer listOfDirectoriesId;

	public Collection() {}

	public Collection(Collection value) {
		this.id = value.id;
		this.name = value.name;
		this.directoryId = value.directoryId;
		this.biobankId = value.biobankId;
		this.listOfDirectoriesId = value.listOfDirectoriesId;
	}

	public Collection(
		Integer id,
		String  name,
		String  directoryId,
		Integer biobankId,
		Integer listOfDirectoriesId
	) {
		this.id = id;
		this.name = name;
		this.directoryId = directoryId;
		this.biobankId = biobankId;
		this.listOfDirectoriesId = listOfDirectoriesId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDirectoryId() {
		return this.directoryId;
	}

	public void setDirectoryId(String directoryId) {
		this.directoryId = directoryId;
	}

	public Integer getBiobankId() {
		return this.biobankId;
	}

	public void setBiobankId(Integer biobankId) {
		this.biobankId = biobankId;
	}

	public Integer getListOfDirectoriesId() {
		return this.listOfDirectoriesId;
	}

	public void setListOfDirectoriesId(Integer listOfDirectoriesId) {
		this.listOfDirectoriesId = listOfDirectoriesId;
	}

    public String getCollectionReadableID() {
		return "(" + id + ") " + directoryId + " " + name;
    }
}
