/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.JOOQ.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * table to store comments on a query
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comment implements Serializable {

	private static final long serialVersionUID = -977173260;

	private Integer   id;
	private Integer   queryid;
	private Timestamp timestamp;
	private Integer   personid;
	private String    text;

	public Comment() {}

	public Comment(Comment value) {
		this.id = value.id;
		this.queryid = value.queryid;
		this.timestamp = value.timestamp;
		this.personid = value.personid;
		this.text = value.text;
	}

	public Comment(
		Integer   id,
		Integer   queryid,
		Timestamp timestamp,
		Integer   personid,
		String    text
	) {
		this.id = id;
		this.queryid = queryid;
		this.timestamp = timestamp;
		this.personid = personid;
		this.text = text;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getQueryid() {
		return this.queryid;
	}

	public void setQueryid(Integer queryid) {
		this.queryid = queryid;
	}

	public Timestamp getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Timestamp timestamp) {
		this.timestamp = timestamp;
	}

	public Integer getPersonid() {
		return this.personid;
	}

	public void setPersonid(Integer personid) {
		this.personid = personid;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}
}
