/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * table to store the timestamp when the connector makes a get request for 
 * new queries
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConnectorLog implements Serializable {

	private static final long serialVersionUID = 1083818690;

	private Integer   id;
	private String    directoryCollectionId;
	private Timestamp lastQueryTime;
	private Timestamp lastNegotiationTime;

	public ConnectorLog() {}

	public ConnectorLog(ConnectorLog value) {
		this.id = value.id;
		this.directoryCollectionId = value.directoryCollectionId;
		this.lastQueryTime = value.lastQueryTime;
		this.lastNegotiationTime = value.lastNegotiationTime;
	}

	public ConnectorLog(
		Integer   id,
		String    directoryCollectionId,
		Timestamp lastQueryTime,
		Timestamp lastNegotiationTime
	) {
		this.id = id;
		this.directoryCollectionId = directoryCollectionId;
		this.lastQueryTime = lastQueryTime;
		this.lastNegotiationTime = lastNegotiationTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDirectoryCollectionId() {
		return this.directoryCollectionId;
	}

	public void setDirectoryCollectionId(String directoryCollectionId) {
		this.directoryCollectionId = directoryCollectionId;
	}

	public Timestamp getLastQueryTime() {
		return this.lastQueryTime;
	}

	public void setLastQueryTime(Timestamp lastQueryTime) {
		this.lastQueryTime = lastQueryTime;
	}

	public Timestamp getLastNegotiationTime() {
		return this.lastNegotiationTime;
	}

	public void setLastNegotiationTime(Timestamp lastNegotiationTime) {
		this.lastNegotiationTime = lastNegotiationTime;
	}
}
