/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Table for queries that are flagged/bookmarked. bookmark options are starred, 
 * archived and ignored.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlaggedQuery implements Serializable {

	private static final long serialVersionUID = 1408236307;
	private static final String starFlag="S";
	private static final String archiveFlag="A";
	private static final String ignoreFlag="I";

	private Integer queryId;
	private Integer personId;
	private String  flag;

	public FlaggedQuery() {}

	public FlaggedQuery(FlaggedQuery value) {
		this.queryId = value.queryId;
		this.personId = value.personId;
		this.flag = value.flag;
	}

	public FlaggedQuery(
		Integer queryId,
		Integer personId,
		String  flag
	) {
		this.queryId = queryId;
		this.personId = personId;
		this.flag = flag;
	}

	public Integer getQueryId() {
		return this.queryId;
	}

	public void setQueryId(Integer queryId) {
		this.queryId = queryId;
	}

	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
	
	public static String getStarflag() {
		return starFlag;
	}

	public static String getArchiveflag() {
		return archiveFlag;
	}

	public static String getIgnoreflag() {
		return ignoreFlag;
	}
}
