/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * query table to contain json text queries
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JsonQuery implements Serializable {

	private static final long serialVersionUID = -1745305764;

	private Integer id;
	private String  jsonText;

	public JsonQuery() {}

	public JsonQuery(JsonQuery value) {
		this.id = value.id;
		this.jsonText = value.jsonText;
	}

	public JsonQuery(
		Integer id,
		String  jsonText
	) {
		this.id = id;
		this.jsonText = jsonText;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getJsonText() {
		return this.jsonText;
	}

	public void setJsonText(String jsonText) {
		this.jsonText = jsonText;
	}
}
