/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Table to store locations of owner
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Location implements Serializable {

	private static final long serialVersionUID = 613334169;

	private Integer id;
	private String  name;
	private String  description;
	private String  directoryId;

	public Location() {}

	public Location(Location value) {
		this.id = value.id;
		this.name = value.name;
		this.description = value.description;
		this.directoryId = value.directoryId;
	}

	public Location(
		Integer id,
		String  name,
		String  description,
		String  directoryId
	) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.directoryId = directoryId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDirectoryId() {
		return this.directoryId;
	}

	public void setDirectoryId(String directoryId) {
		this.directoryId = directoryId;
	}
}
