/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModeratorNetwork implements Serializable {

	private static final long serialVersionUID = -1955666810;

	private Integer personId;
	private Integer networkId;

	public ModeratorNetwork() {}

	public ModeratorNetwork(ModeratorNetwork value) {
		this.personId = value.personId;
		this.networkId = value.networkId;
	}

	public ModeratorNetwork(
		Integer personId,
		Integer networkId
	) {
		this.personId = personId;
		this.networkId = networkId;
	}

	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	public Integer getNetworkId() {
		return this.networkId;
	}

	public void setNetworkId(Integer networkId) {
		this.networkId = networkId;
	}
}
