/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NetworkBiobankLink implements Serializable {

	private static final long serialVersionUID = -1461290281;

	private Integer biobankId;
	private Integer networkId;

	public NetworkBiobankLink() {}

	public NetworkBiobankLink(NetworkBiobankLink value) {
		this.biobankId = value.biobankId;
		this.networkId = value.networkId;
	}

	public NetworkBiobankLink(
		Integer biobankId,
		Integer networkId
	) {
		this.biobankId = biobankId;
		this.networkId = networkId;
	}

	public Integer getBiobankId() {
		return this.biobankId;
	}

	public void setBiobankId(Integer biobankId) {
		this.biobankId = biobankId;
	}

	public Integer getNetworkId() {
		return this.networkId;
	}

	public void setNetworkId(Integer networkId) {
		this.networkId = networkId;
	}
}
