/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationSetting implements Serializable {

	private static final long serialVersionUID = -606464368;

	private Integer notificationSettingId;
	private Integer personId;
	private String  notificationType;
	private String  sendSettings;

	public NotificationSetting() {}

	public NotificationSetting(NotificationSetting value) {
		this.notificationSettingId = value.notificationSettingId;
		this.personId = value.personId;
		this.notificationType = value.notificationType;
		this.sendSettings = value.sendSettings;
	}

	public NotificationSetting(
		Integer notificationSettingId,
		Integer personId,
		String  notificationType,
		String  sendSettings
	) {
		this.notificationSettingId = notificationSettingId;
		this.personId = personId;
		this.notificationType = notificationType;
		this.sendSettings = sendSettings;
	}

	public Integer getNotificationSettingId() {
		return this.notificationSettingId;
	}

	public void setNotificationSettingId(Integer notificationSettingId) {
		this.notificationSettingId = notificationSettingId;
	}

	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	public String getNotificationType() {
		return this.notificationType;
	}

	public void setNotificationType(String notificationType) {
		this.notificationType = notificationType;
	}

	public String getSendSettings() {
		return this.sendSettings;
	}

	public void setSendSettings(String sendSettings) {
		this.sendSettings = sendSettings;
	}
}
