/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * table to store private conversation made on a query between two people(owner 
 * and researcher)
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Offer implements Serializable {

	private static final long serialVersionUID = 1519650346;

	private Integer   id;
	private Integer   queryId;
	private Integer   personId;
	private Integer   offerFrom;
	private Timestamp commentTime;
	private String    text;
	private Integer   biobankInPrivateChat;

	public Offer() {}

	public Offer(Offer value) {
		this.id = value.id;
		this.queryId = value.queryId;
		this.personId = value.personId;
		this.offerFrom = value.offerFrom;
		this.commentTime = value.commentTime;
		this.text = value.text;
		this.biobankInPrivateChat = value.biobankInPrivateChat;
	}

	public Offer(
		Integer   id,
		Integer   queryId,
		Integer   personId,
		Integer   offerFrom,
		Timestamp commentTime,
		String    text,
		Integer   biobankInPrivateChat
	) {
		this.id = id;
		this.queryId = queryId;
		this.personId = personId;
		this.offerFrom = offerFrom;
		this.commentTime = commentTime;
		this.text = text;
		this.biobankInPrivateChat = biobankInPrivateChat;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getQueryId() {
		return this.queryId;
	}

	public void setQueryId(Integer queryId) {
		this.queryId = queryId;
	}

	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	public Integer getOfferFrom() {
		return this.offerFrom;
	}

	public void setOfferFrom(Integer offerFrom) {
		this.offerFrom = offerFrom;
	}

	public Timestamp getCommentTime() {
		return this.commentTime;
	}

	public void setCommentTime(Timestamp commentTime) {
		this.commentTime = commentTime;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Integer getBiobankInPrivateChat() {
		return this.biobankInPrivateChat;
	}

	public void setBiobankInPrivateChat(Integer biobankInPrivateChat) {
		this.biobankInPrivateChat = biobankInPrivateChat;
	}
}
