/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonOffer implements Serializable {

	private static final long serialVersionUID = 2120501406;

	private Integer   personId;
	private Integer   offerId;
	private Boolean   read;
	private Timestamp dateRead;

	public PersonOffer() {}

	public PersonOffer(PersonOffer value) {
		this.personId = value.personId;
		this.offerId = value.offerId;
		this.read = value.read;
		this.dateRead = value.dateRead;
	}

	public PersonOffer(
		Integer   personId,
		Integer   offerId,
		Boolean   read,
		Timestamp dateRead
	) {
		this.personId = personId;
		this.offerId = offerId;
		this.read = read;
		this.dateRead = dateRead;
	}

	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	public Integer getOfferId() {
		return this.offerId;
	}

	public void setOfferId(Integer offerId) {
		this.offerId = offerId;
	}

	public Boolean getRead() {
		return this.read;
	}

	public void setRead(Boolean read) {
		this.read = read;
	}

	public Timestamp getDateRead() {
		return this.dateRead;
	}

	public void setDateRead(Timestamp dateRead) {
		this.dateRead = dateRead;
	}
}
