/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.JOOQ.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * person table which is parent of researcher and owner
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Person implements Serializable {

	private static final long serialVersionUID = 677126974;

	private Integer id;
	private String  authdata;
	private String  persontype;
	private byte[]  personimage;

	public Person() {}

	public Person(Person value) {
		this.id = value.id;
		this.authdata = value.authdata;
		this.persontype = value.persontype;
		this.personimage = value.personimage;
	}

	public Person(
		Integer id,
		String  authdata,
		String  persontype,
		byte[]  personimage
	) {
		this.id = id;
		this.authdata = authdata;
		this.persontype = persontype;
		this.personimage = personimage;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAuthdata() {
		return this.authdata;
	}

	public void setAuthdata(String authdata) {
		this.authdata = authdata;
	}

	public String getPersontype() {
		return this.persontype;
	}

	public void setPersontype(String persontype) {
		this.persontype = persontype;
	}

	public byte[] getPersonimage() {
		return this.personimage;
	}

	public void setPersonimage(byte[] personimage) {
		this.personimage = personimage;
	}
}
