/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * Table for connecting queries with collections
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueryCollection implements Serializable {

	private static final long serialVersionUID = 748233488;

	private Integer   queryId;
	private Integer   collectionId;
	private Boolean   expectConnectorResult;
	private Integer   donors;
	private Integer   samples;
	private Timestamp resultReceivedTime;

	public QueryCollection() {}

	public QueryCollection(QueryCollection value) {
		this.queryId = value.queryId;
		this.collectionId = value.collectionId;
		this.expectConnectorResult = value.expectConnectorResult;
		this.donors = value.donors;
		this.samples = value.samples;
		this.resultReceivedTime = value.resultReceivedTime;
	}

	public QueryCollection(
		Integer   queryId,
		Integer   collectionId,
		Boolean   expectConnectorResult,
		Integer   donors,
		Integer   samples,
		Timestamp resultReceivedTime
	) {
		this.queryId = queryId;
		this.collectionId = collectionId;
		this.expectConnectorResult = expectConnectorResult;
		this.donors = donors;
		this.samples = samples;
		this.resultReceivedTime = resultReceivedTime;
	}

	public Integer getQueryId() {
		return this.queryId;
	}

	public void setQueryId(Integer queryId) {
		this.queryId = queryId;
	}

	public Integer getCollectionId() {
		return this.collectionId;
	}

	public void setCollectionId(Integer collectionId) {
		this.collectionId = collectionId;
	}

	public Boolean getExpectConnectorResult() {
		return this.expectConnectorResult;
	}

	public void setExpectConnectorResult(Boolean expectConnectorResult) {
		this.expectConnectorResult = expectConnectorResult;
	}

	public Integer getDonors() {
		return this.donors;
	}

	public void setDonors(Integer donors) {
		this.donors = donors;
	}

	public Integer getSamples() {
		return this.samples;
	}

	public void setSamples(Integer samples) {
		this.samples = samples;
	}

	public Timestamp getResultReceivedTime() {
		return this.resultReceivedTime;
	}

	public void setResultReceivedTime(Timestamp resultReceivedTime) {
		this.resultReceivedTime = resultReceivedTime;
	}
}
