/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Table for queries that have one or more attachments uploaded.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueryAttachment implements Serializable {

	private static final long serialVersionUID = -65557294;

	private Integer id;
	private Integer queryId;
	private String  attachment;

	public QueryAttachment() {}

	public QueryAttachment(QueryAttachment value) {
		this.id = value.id;
		this.queryId = value.queryId;
		this.attachment = value.attachment;
	}

	public QueryAttachment(
		Integer id,
		Integer queryId,
		String  attachment
	) {
		this.id = id;
		this.queryId = queryId;
		this.attachment = attachment;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getQueryId() {
		return this.queryId;
	}

	public void setQueryId(Integer queryId) {
		this.queryId = queryId;
	}

	public String getAttachment() {
		return this.attachment;
	}

	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}
}
