/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Table for connecting queries with collections
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueryCollection implements Serializable {

	private static final long serialVersionUID = -559378921;

	private Integer queryId;
	private Integer collectionId;
	private Boolean expectConnectorResult;

	public QueryCollection() {}

	public QueryCollection(QueryCollection value) {
		this.queryId = value.queryId;
		this.collectionId = value.collectionId;
		this.expectConnectorResult = value.expectConnectorResult;
	}

	public QueryCollection(
		Integer queryId,
		Integer collectionId,
		Boolean expectConnectorResult
	) {
		this.queryId = queryId;
		this.collectionId = collectionId;
		this.expectConnectorResult = expectConnectorResult;
	}

	public Integer getQueryId() {
		return this.queryId;
	}

	public void setQueryId(Integer queryId) {
		this.queryId = queryId;
	}

	public Integer getCollectionId() {
		return this.collectionId;
	}

	public void setCollectionId(Integer collectionId) {
		this.collectionId = collectionId;
	}

	public Boolean getExpectConnectorResult() {
		return this.expectConnectorResult;
	}

	public void setExpectConnectorResult(Boolean expectConnectorResult) {
		this.expectConnectorResult = expectConnectorResult;
	}
}
