/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * Table for the relationship between all the persons(owners) and the queries 
 * that they have replied to.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueryPerson implements Serializable {

	private static final long serialVersionUID = -83446396;

	private Integer   queryId;
	private Integer   personId;
	private Timestamp queryLeavingTime;

	public QueryPerson() {}

	public QueryPerson(QueryPerson value) {
		this.queryId = value.queryId;
		this.personId = value.personId;
		this.queryLeavingTime = value.queryLeavingTime;
	}

	public QueryPerson(
		Integer   queryId,
		Integer   personId,
		Timestamp queryLeavingTime
	) {
		this.queryId = queryId;
		this.personId = personId;
		this.queryLeavingTime = queryLeavingTime;
	}

	public Integer getQueryId() {
		return this.queryId;
	}

	public void setQueryId(Integer queryId) {
		this.queryId = queryId;
	}

	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	public Timestamp getQueryLeavingTime() {
		return this.queryLeavingTime;
	}

	public void setQueryLeavingTime(Timestamp queryLeavingTime) {
		this.queryLeavingTime = queryLeavingTime;
	}
}
