/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Table for all the locations that have replied to a query.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueryLocation implements Serializable {

	private static final long serialVersionUID = -100120740;

	private Integer queryId;
	private Integer locationId;

	public QueryLocation() {}

	public QueryLocation(QueryLocation value) {
		this.queryId = value.queryId;
		this.locationId = value.locationId;
	}

	public QueryLocation(
		Integer queryId,
		Integer locationId
	) {
		this.queryId = queryId;
		this.locationId = locationId;
	}

	public Integer getQueryId() {
		return this.queryId;
	}

	public void setQueryId(Integer queryId) {
		this.queryId = queryId;
	}

	public Integer getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}
}
