/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RequestStatus implements Serializable {

	private static final long serialVersionUID = -910212351;

	private Integer   id;
	private Integer   queryId;
	private String    status;
	private Timestamp statusDate;
	private Integer   statusUserId;

	public RequestStatus() {}

	public RequestStatus(RequestStatus value) {
		this.id = value.id;
		this.queryId = value.queryId;
		this.status = value.status;
		this.statusDate = value.statusDate;
		this.statusUserId = value.statusUserId;
	}

	public RequestStatus(
		Integer   id,
		Integer   queryId,
		String    status,
		Timestamp statusDate,
		Integer   statusUserId
	) {
		this.id = id;
		this.queryId = queryId;
		this.status = status;
		this.statusDate = statusDate;
		this.statusUserId = statusUserId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getQueryId() {
		return this.queryId;
	}

	public void setQueryId(Integer queryId) {
		this.queryId = queryId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Timestamp getStatusDate() {
		return this.statusDate;
	}

	public void setStatusDate(Timestamp statusDate) {
		this.statusDate = statusDate;
	}

	public Integer getStatusUserId() {
		return this.statusUserId;
	}

	public void setStatusUserId(Integer statusUserId) {
		this.statusUserId = statusUserId;
	}
}
