/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * researcher table - one of the child's of the person table 
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Researcher implements Serializable {

	private static final long serialVersionUID = 741952305;

	private Integer id;

	public Researcher() {}

	public Researcher(Researcher value) {
		this.id = value.id;
	}

	public Researcher(
		Integer id
	) {
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
}
