/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import de.samply.bbmri.negotiator.jooq.enums.RoleType;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Table for different roles of a user.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role implements Serializable {

	private static final long serialVersionUID = 1826406488;

	private RoleType roleType;
	private Integer  personId;

	public Role() {}

	public Role(Role value) {
		this.roleType = value.roleType;
		this.personId = value.personId;
	}

	public Role(
		RoleType roleType,
		Integer  personId
	) {
		this.roleType = roleType;
		this.personId = personId;
	}

	public RoleType getRoleType() {
		return this.roleType;
	}

	public void setRoleType(RoleType roleType) {
		this.roleType = roleType;
	}

	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}
}
