/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Table for queries that are tagged by names e.g. colonCancer,SkinCancer 
 * etc. Tag names need to be decided .
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Taggedquery implements Serializable {

	private static final long serialVersionUID = -513837543;

	private Integer queryid;
	private Integer tagid;

	public Taggedquery() {}

	public Taggedquery(Taggedquery value) {
		this.queryid = value.queryid;
		this.tagid = value.tagid;
	}

	public Taggedquery(
		Integer queryid,
		Integer tagid
	) {
		this.queryid = queryid;
		this.tagid = tagid;
	}

	public Integer getQueryid() {
		return this.queryid;
	}

	public void setQueryid(Integer queryid) {
		this.queryid = queryid;
	}

	public Integer getTagid() {
		return this.tagid;
	}

	public void setTagid(Integer tagid) {
		this.tagid = tagid;
	}
}
