/**
 * This class is generated by jOOQ
 */
package de.samply.bbmri.negotiator.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Table for queries that are tagged by names e.g. colonCancer,SkinCancer 
 * etc. Tag names need to be decided .
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaggedQuery implements Serializable {

	private static final long serialVersionUID = 1464867385;

	private Integer queryId;
	private Integer tagId;

	public TaggedQuery() {}

	public TaggedQuery(TaggedQuery value) {
		this.queryId = value.queryId;
		this.tagId = value.tagId;
	}

	public TaggedQuery(
		Integer queryId,
		Integer tagId
	) {
		this.queryId = queryId;
		this.tagId = tagId;
	}

	public Integer getQueryId() {
		return this.queryId;
	}

	public void setQueryId(Integer queryId) {
		this.queryId = queryId;
	}

	public Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}
}
