name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Generate settings.xml for Maven Builds
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          mirrors: >
            [
              {
                "id": "nexus",
                "mirrorOf": "*",
                "url": "http://78.128.250.32:8081/repository/maven-public/"
              }
            ]
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
