name: Java CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test with maven
        run: mvn -B package

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
