name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Generate settings.xml for Maven Builds
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          mirrors: >
            [
              {
                "id": "nexus",
                "mirrorOf": "central",
                "url": "http://78.128.250.32:8081/repository/maven-public/"
              }
            ]
      - name: Build with Maven
        run: mvn package

      - name: Run tests and collect coverage
        run: mvn -B test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
