name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Generate settings.xml for Maven Builds
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          mirrors: >
            [
              {
                "id": "nexus",
                "mirrorOf": "*",
                "url": "http://78.128.250.32:8081/repository/maven-public/"
              }
            ]
      - name: Build with Maven
        run: mvn package

  test-coverage:
    if: ${{ github.event_name != 'schedule' }}

    needs: [ test ]

    runs-on: ubuntu-20.04

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Cache Local Maven Repo
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-temurin-17-maven-test-coverage-${{ hashFiles('**/deps.edn') }}

      - name: Test Coverage
        run: make test-coverage

      - name: Codecov Upload
        uses: codecov/codecov-action@v3
        with:
          name: codecov-umbrella
          file: modules/**/target/coverage/codecov.json
          fail_ci_if_error: true
