name: CI build

on:
  schedule:
    - cron: '0 10 * * *' # every day at 10am
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DISABLE_ERRORS: true


  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Generate settings.xml for Maven Builds
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          mirrors: >
            [
              {
                "id": "central",
                "mirrorOf": "central",
                "url": "http://nexus.bbmri-eric.eu:8081/repository/maven-public/"
              }
            ]

      - name: Build and test with maven
        run: mvn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3


  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@v4
        with:
          images: |
            bbmrieric/negotiator
          tags: |
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          outputs: type=docker,dest=/tmp/negotiator.tar

      - name: Upload Negotiator image
        uses: actions/upload-artifact@v3
        with:
          name: negotiator-image
          path: /tmp/negotiator.tar


  image-scan:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Download Image
        uses: actions/download-artifact@v3
        with:
          name: negotiator-image
          path: /tmp/negotiator.tar

      - name: Load Image
        run: docker load --input /tmp/negotiator.tar

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: negotiator:latest
          format: sarif
          output: trivy-results.sarif
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif


