name: CI build

on:
  schedule:
    - cron: '0 10 * * *' # every day at 10am
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master

jobs:
  codeQL:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2


  test:
    needs: [ codeQL ]
    runs-on: ubuntu-22.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Generate settings.xml for Maven Builds
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          mirrors: >
            [
              {
                "id": "central",
                "mirrorOf": "central",
                "url": "http://nexus.bbmri-eric.eu:8081/repository/maven-public/"
              }
            ]

      - name: Run unit tests
        run: mvn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3


  build:
    needs: [ test ]
    runs-on: ubuntu-22.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Generate settings.xml for Maven Builds
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          mirrors: >
            [
              {
                "id": "central",
                "mirrorOf": "central",
                "url": "http://nexus.bbmri-eric.eu:8081/repository/maven-public/"
              }
            ]
      - name: Build with maven
        run: mvn -B package -DskipTests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: negotiator:latest
          outputs: type=docker,dest=/tmp/negotiator.tar

      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: negotiator-image
          path: /tmp/negotiator.tar


  image-scan:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Download Image
        uses: actions/download-artifact@v3
        with:
          name: negotiator-image
          path: /tmp

      - name: Load Image
        run: docker load --input /tmp/negotiator.tar

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: negotiator:latest
          format: sarif
          output: trivy-results.sarif
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif


